### PR TITLE
Fix sorting

### LINKED ISSUE #4: Sorting is a little wonky
Video: https://streamable.com/wpdtgj

I'm assuming it's alphabetical, but there's several items that don't want to be sorted as such. And one item - **M**etal Ingot - that's OK with being sorted before and after **N**ails.

There's also the Bee Jar, which should be sorted at the beginning, but perhaps it's a brand new item and hasn't been added to the code yet. I haven't taken a look at the code: 

image

In any case, thank you for this mod. I like staying organized.

EDIT: This is also happening with **G**iant Clams: https://streamable.com/ssmhev

### LINKED ISSUE #5: Sorting full stacks moves last stack to the end
If the inventory or container has a stackable item with only full stacks then the last stack for that item will be moved to the end of the inventory/container.

### PR DESCRIPTION
**Pull request by dcsobral**
Fixes #5  by ensuring items are never moved forward of their current position when compacting.
Fixes #4  by using the localized name when sorting.

This also updates references to the current game and mod loader version, and replaces the build bat with the current one.

### CODE REVIEW

**Comment by dcsobral** [comment]
@made-by-traxam Would you like me to PR this to your repository? The only reason I didn't create this there is that the issue tracker is disabled on your repo.

**Comment by mcglonelevi** [comment]
I am no longer actively maintaining this repo.  @made-by-traxam should implement and test these changes.

**Comment by made-by-traxam** [comment]
> @made-by-traxam Would you like me to PR this to your repository? The only reason I didn't create this there is that the issue tracker is disabled on your repo.

Yeah, that would be nice. I've enabled the issue tracker now, not sure why it was disabled in the first place.

> I am no longer actively maintaining this repo. @made-by-traxam should implement and test these changes.

Will do :)

**Comment by dcsobral** [comment]
Closing this here.

**Pull request closed without merging**
